export enum PersonStage {
  CHERISH = 'CHERISH',
  NURTURE = 'NURTURE',
  EXPLORE = 'EXPLORE',
  WISHLIST = 'WISHLIST',
  MAINTAIN = 'MAINTAIN',
  OTHERS = 'OTHERS',
  NOT_SPECIFIED = 'NOT_SPECIFIED',
}
